# Generated by Django 2.1.3 on 2018-11-29 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoCocina', models.CharField(max_length=50)),
                ('alergenos', models.CharField(max_length=150)),
                ('precio', models.FloatField()),
                ('nombre', models.CharField(max_length=150)),
                ('descripccion', models.TextField()),
                ('ingredientes', models.TextField()),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
